image: node:18

# workflow:
#   rules:
#   - if: '$CI_PROJECT_NAMESPACE != "asacolips-projects"'
#     when: never
#   - when: always

before_script:
  - apt-get update
  - apt-get install zip

cache:
  paths:
    - node_modules/

# test-build:
#   stage: test
#   script:
#     - export
#     - npm ci
#     - npm run build:noVite
#     - npm run vite:build:preview
#   artifacts:
#     expire_in: 7 days
#     paths:
#       - public
#   environment:
#     name: 'Preview'
#     url: "https://asacolips-projects.gitlab.io/-/foundry-mods/archmage/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
#   variables:
#     PUBLIC_URL: "/-/foundry-mods/archmage/-/jobs/$CI_JOB_ID/artifacts/public"
#     GIT_SUBMODULE_STRATEGY: recursive
#   except:
#     - beta
#     - tags

build-beta:
  stage: build
  script:
    - export
    - npm ci
    - npm run build:prod
    - node update-build-tags.js --branch=$CI_COMMIT_BRANCH --gitlabpath=$CI_PROJECT_PATH --jobname=$CI_JOB_NAME --versionpre=$CI_PIPELINE_IID
    - cd dist && zip -q ../archmage.zip -r . && cd ../
  artifacts:
    paths:
      - archmage.zip
      - system.json
  only:
    - beta

build-prod:
  stage: build
  script:
    - export
    - npm ci
    - npm run build:prod
    - node update-build-tags.js --branch=$CI_COMMIT_BRANCH --gitlabpath=$CI_PROJECT_PATH --jobname=$CI_JOB_NAME  --tag=$CI_COMMIT_TAG
    - cd dist && zip -q ../archmage.zip -r . && cd ../
  artifacts:
    paths:
      - archmage.zip
      - system.json
  only:
    - tags