name: Release Creation

on: 
  push:
    tags:
    - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Gulp build
      uses: elstudio/actions-js-build/build@v2
      with:
        args: build

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
  
    #Substitute the Manifest and Download URLs in the system.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'system.json'
      env:
        version: ${{ steps.get_version.outputs.VERSION }}
        manifest: ""
        download: https://patreon.azurewebsites.net/api/download/toolkit13/${{ steps.get_version.outputs.VERSION }}/system.zip

    # create a zip file with all files required by the system to add to the release
    - run: zip -r ./system.zip system.json template.json assets/ condition-maps/ css/ images/ languages/ licenses/ module/ packs/ scripts/ styles/ templates/ dist/

    # Create a release for this specific version
    - name: Create Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.get_version.outputs.VERSION }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './system.json,./system.zip'
        
    - name: Azure Blob Storage Upload
      # You may pin to the exact commit or the version.
      # uses: bacongobbler/azure-blob-storage-upload@779a18b594a1a7cf5412645e06c856324a8b01e5
      uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      with:
        # The connection string for the storage account
        connection_string: ${{ secrets.ConnectionString }}
        # The name of the storage account container these assets will be uploaded to
        container_name: toolkit13
        # The name of the directory you want to upload
        source_dir: .
        extra_args: '--destination-path "${{ steps.get_version.outputs.VERSION }}"'
